on:
  workflow_call:
    inputs:
      abc:
        required: true
        default: hey
        type: string

jobs:
  called_job:
    runs-on: ubuntu-latest
    steps:
      - name: Hello
        run: echo "${{ inputs.abc }}"
