on:
  workflow_dispatch:
    inputs:
      abc:
        required: true
        type: string

jobs:
  test:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Hello
        run: echo "${{ inputs.abc }}"
      - name: git clone
        uses: actions/checkout@v4
      - name: Merge
        run: gh pr merge --merge
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
