on:
  workflow_call:
    inputs:
      abc:
        required: true
        type: string

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Hello
        run: echo "${{ inputs.abc }}"
      - name: Merge
        run: gh pr merge
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
