name: PostgreSQL container service
on: push

jobs:
  my-container-job:
    runs-on: ubuntu-latest
    container: python:3.11

    services:
      postgres:
        image: postgres:16.3
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Install dependency
        run: pip install psycopg2-binary

      - name: Connect to postgresql
        run: |
          python -c "
          import psycopg2
          psycopg2.connect('postgres:postgres@localhost')
          "
