on:
  push:
    branches:
      - nobranch

jobs:
  my-container-job:
    runs-on: ubuntu-latest
    container: python:3.11
    services:
      my-service:
        image: postgres:16.3
        env:
          POSTGRES_PASSWORD: p4ss
    steps:
      - name: Install dependency
        run: pip install psycopg2-binary
      - name: Connect to postgresql
        run: |
          python -c "
          import psycopg2 as p
          p.connect('postgresql://postgres:p4ss@my-service/postgres')
          "
